### ISSUE TITLE
JOSS REVIEW: add default value for glass_plot_kws and stat_plot_kws

### ISSUE THREAD

**Issue by andrewheusser** [miykael/atlasreader#102]
Very minor, but add a default value (e.g. `None`) for:

glass_plot_kws: dict or None, optional
Additional keyword arguments to pass to nilearn.plotting.plot_glass_brain.

stat_plot_kws: dict or None, optional
Additional keyword arguments to pass to nilearn.plotting.plot_stat_map.

**Comment by miykael** [comment]
Changes are implemented with https://github.com/miykael/atlasreader/pull/107/commits/23cae1f96f07191f715c7cabf7e87194af584519.

**Comment by andrewheusser** [comment]
👍
