### ISSUE TITLE
JOSS REVIEW: clarify additional params

### ISSUE THREAD

**Issue by andrewheusser** [miykael/atlasreader#103]
The additional parameters API documentation section lays out the API for `create_output`, but as it reads, it seems like the documentation is describing a function called `atlasreader`.  I'd suggest replacing `atlasreader` at the top with `atlasreader.create_output` or just `create_output`.

**Comment by miykael** [comment]
You're right. Using `atlasreader` for the terminal and python implementation is not correct. I've repaced `atlasreader` with "AtlasReader" in most parts and wrote `atlasreader.create_output` where you suggested.

See https://github.com/miykael/atlasreader/pull/107/commits/8b42ce19440b1e28be462398b5b5ef8206b789a4.

**Comment by andrewheusser** [comment]
👍
