### ISSUE TITLE
JOSS REVIEW: paper wording suggestion

### ISSUE THREAD

**Issue by andrewheusser** [miykael/atlasreader#104]
The paper looks great, just one suggestion. You state:

"For example, using functional MRI, we are able to pinpoint where in the brain a certain cognitive process shows higher activation than usual."

"than usual" is a little ambiguous.  I'd suggest changing that sentence to something like:

"For example, using functional MRI, we are able to pinpoint where in the brain a cognitive task elicits higher activation relative to a control." (here, the control can mean another condition or non-task timepoints).

Happy to discuss further if you don't agree.

**Comment by miykael** [comment]
Thank you for your input. I agree with you and implemented your changes with https://github.com/miykael/atlasreader/pull/107/commits/3134231debfb44f6b8f88556a21da6faef4fe0bc.

**Comment by andrewheusser** [comment]
👍
