### ISSUE TITLE
JOSS REVIEW: scipy and sklearn missing DOIs

### ISSUE THREAD

**Issue by andrewheusser** [miykael/atlasreader#105]
If they are available, please add DOIs to the scipy and sklearn references

**Comment by miykael** [comment]
Surprisingly, both of them don't have a DOI. I've looked again and wasn't able to find one.
But I've added the sklearn URL to the reference (scipy had already one), with this commit https://github.com/miykael/atlasreader/pull/107/commits/b2628f4d4182343641b857a824afd4d0c870d22f.

**Comment by andrewheusser** [comment]
👍
