### ISSUE TITLE
ar.read_atlas_peak(atlastype) not working if atlastype is 'desikan_killiany' str

### ISSUE THREAD

**Issue by pfdamasceno** [miykael/atlasreader#109]
Hi all, 

While using `ar.read_atlas_peak(atlastype, coordinate, prob_thresh=5)` to inquire the region a voxel belongs to, we noticed that the documentation suggests `atlastype` should be a `str`. 

The following code doesn't not work:

```
ar.read_atlas_peak(“desikan_killiany”, [10,10,10])
```

while the code below does work:

```
ar.read_atlas_peak(ar.get_atlas("desikan_killiany"),[10,10,10])
```

This suggests `atlastype` should be the atlas itself, not a string. Is that correct? If so, let me know if a PR is needed or if one of you can fire a hot fix for the documentation...

Thanks.

ps: Congrats on shipping to JOSS =)

**Comment by miykael** [comment]
Hi @pfdamasceno,

Thank you for pointing this out. I've corrected the function (https://github.com/miykael/atlasreader/pull/110) so that it works now with `"desikan_klilliany"`. 

And thanks about the JOSS comment, we're very happy about it :-)

**Comment by miykael** [comment]
Updated version can be installed with `pip install -U atlasreader`
