### ISSUE TITLE
python dependency ?

### ISSUE THREAD

**Issue by wlyzgw** [miykael/atlasreader#117]
Thanks for creating this package and it makes the work much easier. I am currently using it to analyze my data. Bear with me if my questions are too simple since I am new to python. After successfully installing it under python2.7, I got the following error messages " from atlasreader.info import __version__.....ImportError: No module named info", is this due to my older python version? 
I am using anaconda python 2.7 environment since another package pymvpv2 was using python2.7. Is there a way that I can solve this different python versions dependency problem?
I really appreciate your help.

**Comment by miykael** [comment]
Hello, thank you for feedback. I've briefly tried to install it under a Python 2.7 environment but wasn't able to get it run without some major investigation. The issue is, `atlasreader` wasn't written for a Python 2.7 framework and might not work - especially as connected packages, such as `nilearn` might be missing some functionalities in earlier versions. For this reason, I would recommend to stick to Python 3.6 or higher when using `atlasreader`.

However, being a big fan (and user) of pymvpa, I can relate to the version issue here. What I would recommend is to use something like [anaconda](https://www.anaconda.com/products/individual) to create two python environments, one with Python 2.7 and one with Python 3.7. Like this it will be possible to do the computations with PyMVPA in one environment and then switch to the other one for `atlasreader`. Would that solve your issue?

**Comment by wlyzgw** [comment]
Hi Michael,Thanks so much for your fast reply and I have installed anaconda to have two environments. I have made some progress reading in my own data and using skbold package to start the analysis. I realized that the contrast names were used as mvp.y labels so it will be quite easy to have contrasts divided into conditions already. While my data has 30 food pictures (then 30 ratings by keypressing) and I named the contrasts as  F1,F2.......F30, and there are also some task-relevant contrasts like keypress and missing trials (I removed those as in the code). I want to use high and low ratings as labels (median split, and then delete some trials so high vs low trails ratio is 1:1) so I can't use mvp.y directly as my labels. I know I can create a list y as new labels but I didn't find a tutorial online and I have tried to add a list Y in the mvpwithin () function but failed. I have a csv file with the picture number and the matching keypress number, should I read in this file somewhere? I attached my current code but the current labels will be only food picture numbers as I explained. 
Any feedback will be appreciated since I am just a new learner of python. Really appreciate your time and patience.


subject_list=['2003','2056','2016','2056','2061','2066','2067','2070','2079','2080','2084','2086',
             '2088','2091','2105','2107','2108','2110','2114','2117','2118','2123','2124','2125','2135','2137']


roi_dir='/Volumes/backup_2/BID/OFCmask/'

feat_dirs = glob(op.join('..', 'data', 'pi*', 'wm.feat'))

# set up cross validation
n_folds = 6
skf = StratifiedKFold(n_splits=n_folds)

#mask 
# 

mask_threshold=0.5
base_dir='/Volumes/backup_2/BID/OFCmask/'
empathy_map=glob(opj(base_dir,'LOFC.nii'))[0]



# Keep track of all performance estimates
all_performance = np.zeros(len(subject_list))
all_dummy_performance = np.zeros(len(subject_list))

roi_name='LOFC'


for i_sub,subj in enumerate(subject_list):


    source=glob(op.join( '/Volumes', 'backup_2', 'BID',subj,'analysis','*+.feat'))
    mvp = MvpWithin(source=source, read_labels=True,
                        ref_space='epi', statistic='tstat',
                        remove_zeros=True,
                       remove_contrast = ['BID0','BID1','BID3','BID5','KP','FB'],
                        mask=empathy_map,
                        mask_threshold=mask_threshold
                       )
    mvp.create()
            
                    



> Hello, thank you for feedback. I've briefly tried to install it under a Python 2.7 environment but wasn't able to get it run without some major investigation. The issue is, `atlasreader` wasn't written for a Python 2.7 framework and might not work - especially as connected packages, such as `nilearn` might be missing some functionalities in earlier versions. For this reason, I would recommend to stick to Python 3.6 or higher when using `atlasreader`.
> 
> However, being a big fan (and user) of pymvpa, I can relate to the version issue here. What I would recommend is to use something like [anaconda](https://www.anaconda.com/products/individual) to create two python environments, one with Python 2.7 and one with Python 3.7. Like this it will be possible to do the computations with PyMVPA in one environment and then switch to the other one for `atlasreader`. Would that solve your issue?

**Comment by Remi-Gau** [comment]
I think this can probably be closed
