### ISSUE TITLE
run tests on github action instead of travis

### ISSUE THREAD

**Issue by Remi-Gau** [miykael/atlasreader#125]
- should probably also take care of sending the coverage report to codecov

**Comment by miykael** [comment]
Thank you for this suggestion and the work in https://github.com/miykael/atlasreader/pull/131 that will that make happen. I've corrected the 'last' bug and the unittests are now passing - there's only a coveralls issue remaining.

Once the PR https://github.com/miykael/atlasreader/pull/131 is merged, this issue can be closed.
