### ISSUE TITLE
add more "formatting" ?

### ISSUE THREAD

**Issue by Remi-Gau** [miykael/atlasreader#130]
Things I can easily implement:
- black
- isort
- pyupgrade
- codespell
- pre-commit

probably to match the config we use on the nilearn side: https://github.com/nilearn/nilearn/blob/main/.pre-commit-config.yaml

**Comment by Remi-Gau** [comment]
let me know what you think

**Comment by miykael** [comment]
I'm not familiar with pyupgrade but know the others. So yes, feel free to add any/all of them or make it comparable to nilearn. Thank you!
