### ISSUE TITLE
Less clusters in csv file than output figures

### ISSUE THREAD

**Issue by vigwma** [miykael/atlasreader#145]
Thanks for this absolutely amazing toolbox!

I have used it successfully so far. 
Just one issue occured: For one contrast image the atlas reader detects 20 clusters. However the csv file shows only information for 9 clusters. 
Is that behavior expected or do I need to change the settings somewhere to display the region information for all cluster?

Thanks!

**Comment by miykael** [comment]
Hello, thanks for your question. I'm unfortunately not sure what's happening here. If it detects 20 clusters it should also report them. Only possible explanation (which it shouldn't) is that you chose some particular threshold or distance parameters that make it to not report the smallest clusters.

**Comment by vigwma** [comment]
Thanks for your reply. I chose cluster_extent to be 0 as well as voxel_thresh. For everything else I left the default values.

**Comment by miykael** [comment]
That might be the issue. I'm not sure how the algorithm reacts to having both of them 0. If you set them both slightly above 0 that might do the trick. So cluster_extent=1 (as it needs to be an integer, otherwise the parameter is used as a percentile) and voxel_thresh=0.1 (or something similar).

**Comment by Remi-Gau** [comment]
@vigwma 
Do you think you could share a code example so we an reproduce the issue?

Ideally derived from our example code in this notebook?
https://github.com/miykael/atlasreader/blob/master/notebooks/atlasreader.ipynb

**Comment by vigwma** [comment]
Hi @Remi-Gau,
thank you so much for the response! 
I am very sorry for not replying so far. I had to work on a different part of the project. Now I was able to look at it again. I realized it was a file issue unrelated to the package.
The package works perfectly now. Thank you so much!

**Comment by Remi-Gau** [comment]
ok I think this can be closed then
@miykael
