### ISSUE TITLE
Packaging the toolbox

### ISSUE THREAD

**Issue by miykael** [miykael/atlasreader#21]
@rmarkello - I'm not really sure what the `setup.py` file implies. But do we want to package the toolbox with `pypi` so that people can download it with a pip command? Do you otherwise know how to put it into a conda framework?

**Comment by miykael** [comment]
Is everybody ok if we put the toolbox on pypi? @rmarkello, @danjgale, 
Are there any recommendations for names? Should we keep `mni_atlas_reader`?  so...

```python
import mni_atlas_reader as mar
```

**Comment by miykael** [comment]
I setup a PyPi thing once, so I think I could do it again as well. But I'm also happy to let you do it. There might be "hidden" things that I missed in my other project.

Considering names: Yes, you're right. underscores are stupid. I was young, back than...
I like your proposals, but what about `atlasreader` or `mnireader`?

**Comment by danjgale** [comment]
I like `atlasreader`! Speaks more closely to the goal of the library.

**Comment by miykael** [comment]
Ross - Which one do you prefer?

**Comment by rmarkello** [comment]
`atlasreader` sounds good to me!

**Comment by miykael** [comment]
So, I will rename this repo to atlasreader, ok for you? I have no idea if you also have to rename your forks?

**Comment by rmarkello** [comment]
Sounds good to me! We'll have to change all the references to `mni_atlas_reader` in the codebase, as well, but that should be as a pretty straightforward find-and-replace. 

Regarding renaming the forks: unsure, but we _will_ have to update remotes on our local copies. Nonetheless, is should be pretty easy to do!

**Comment by miykael** [comment]
`mni_atlas_reader` is the past - welcome to `atlasreader`!

**Comment by rmarkello** [comment]
:tada: :tada: :tada:

The name of the repo on forks doesn't automatically update, but I also don't think it's a problem either way. We'll see how the next PR goes, though!

**Comment by KirstieJane** [comment]
Love the new name ✨ 👾

**Comment by danjgale** [comment]
Closed with #5, #7, and #34 (and possibly some others I may have missed!)
