### ISSUE TITLE
Publication in Journal of Open Source Software (JOSS)

### ISSUE THREAD

**Issue by miykael** [miykael/atlasreader#25]
@rmarkello and @danjgale - what do you guys think about publishing this toolbox in a short paper?

I haven't done it but I thought of the "Research and Ideas" (RIO) paper or perhaps the F1000, as mentioned by Ariel or was it Cameron? I imagine something short as this: https://riojournal.com/article/12342/

We can also just package into a zenodo thingy, but I like RIO or F1000 more as it is also considered by google scholar.

**Comment by KirstieJane** [comment]
I think this is a great idea!! Super interested in being involved if I can be of help!✨✨

**Comment by danjgale** [comment]
Excellent idea! I'm all for it

**Comment by miykael** [comment]
Perfect, we just need to figure out which format makes the most sense, i.e. RIO or F1000 (or something completely different?). What do you guys think?

Considering functionality, I think it's only "missing" that it reads out multiple peaks per cluster (as described in https://github.com/miykael/mni_atlas_reader/issues/23).

Or is there something else missing?

**Comment by miykael** [comment]
I mentioned RIO and F1000, but we could also publish in [JOSS](https://joss.theoj.org/). I think it would be a perfect journal for such a software. What do you guys think?

**Comment by miykael** [comment]
Now that this all is done, I think we're ready for submitting this to JOSS.

@rmarkello, @danjgale, @PeerHerholz and @KirstieJane, do you have any more issues, concerns or, comments or are you ok with submission?

**Comment by PeerHerholz** [comment]
whoop whoop!

Yeah, thx @miykael! This is amazing and I'm super happy to be a part of atlasreader.

P.S.: In the light of recent events, I'm thinking about adding @rmarkello's affiliation to my information. In case you're going to do some smaller changes/pushes, please feel free to add it. Otherwise, I'll do a small PR.

**Comment by miykael** [comment]
I'm very happy that both of you are part of this as well. Feels great to have something like this finished and ready to publish :-)

@PeerHerholz, you can just make a new PR with your affiliation and I will merge it then. I think I anyhow need to create a new version for the JOSS submission.

**Comment by miykael** [comment]
@PeerHerholz - I've just updated your affiliation.

**Comment by KirstieJane** [comment]
Sorry for the slow reply! This looks awesome and ready to go 🚀 🌟 ✨ 🌙

**Comment by danjgale** [comment]
Looks great, really pleased with it! Good to submit imo

**Comment by miykael** [comment]
Perfect! Thanks for all the feedback, I will close this issue and start the submission process.
