### ISSUE TITLE
Example notebook needs fixing after being moved to notebooks/  and api changes

### ISSUE THREAD

**Issue by danjgale** [miykael/atlasreader#32]
The example notebook has some broken paths right now because it was relocated to `notebooks/`. As well, `create_output()`, as is, breaks with the new stylistic changes (see #29). Both of these are good things of course, and I'm working on fixes for both in the example notebook.

**Comment by miykael** [comment]
Were both issues taken care of with https://github.com/miykael/atlasreader/pull/33? If so, than you can close this issue @danjgale.

By the way, I just learned this now from @rmarkello, but if you include something like "Closes https://github.com/miykael/atlasreader/pull/33" at the beginning of your pull request (like here https://github.com/miykael/atlasreader/pull/31) - this will cause the issue to be closed, when the PR is approved.

I need to read up on this mysefl: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by danjgale** [comment]
Yes, both issues were taken care of in #33. Cheers!
