### ISSUE TITLE
CSV Output - peak and mean cluster value

### ISSUE THREAD

**Issue by miykael** [miykael/atlasreader#39]
Not sure if this is just the case for me, but I ran `atlasreader` on some data and I observed two particular issues in the CSV tables.

 - for **peaks.csv** - all the `peak_values` where `0.0`
 - for **clusters.csv** - `mean_value` is accurate to ~13 decimal places

Is that the same for others as well? Also, what do you think about restricting the number of decimal places for mean value? Or is just a stylistic obsession of mine, to round decimal numbers to a few decimal places?

**Comment by rmarkello** [comment]
The `peak_values` shouldn't be 0!!! That's possibly a bug, though it'd be difficult to tell without your data to test on. I'll try running it on a few other things to see if I can recreate.

As for `mean_value` in the **clusters.csv** file: I definitely agree. I'm personally a fan of 2-3 decimals. What we you thinking?

**Comment by miykael** [comment]
**clusters.csv** - I was also thinking of 2-4 decimals. But that might be problematic. Let's imagine somebody loads an image that only has values between 0.00001 and 0.0001. It shouldn't be on us to force a specific accuracy. So perhaps it's even better to move it to scientific notation?

**Comment by rmarkello** [comment]
We can do that! But don't we need to specify the number of significant digits in that case, too? I.e., if there's a value of `0.00001152315` would we print `1.152315e-5` or `1.15e-5`?

**Comment by KirstieJane** [comment]
+1 on all these points.

From [this stackoverflow answer](https://stackoverflow.com/questions/34032855/rounding-scientific-notation-in-python), the [new format](https://docs.python.org/3/library/string.html#string-formatting) for string outputs to 3 significant figures in scientific format would be: `'{:0.3e}'.format(x)`

For more details see: https://docs.python.org/3/library/string.html#format-specification-mini-language

**Comment by miykael** [comment]
Thanks @KirstieJane - I like the `'{:0.3e}'.format(x)` version. But I'm hesitating to increase the decimal to 4-6 significant figures. Higher precision might be relevant for people who want to run additional statistics on those values, no?

**Comment by KirstieJane** [comment]
Yep - I think 5 is totally fine in scientific notation. I can't imagine anyone needing much more than that (insert something something about MRI being a noisy measure in the first place!!)

**Comment by KirstieJane** [comment]
Gah - just had a thought - is writing out the numbers in scientific notation going to be a problem for reading back in the values to another piece of software or programme?

**Comment by miykael** [comment]
Very good point @KirstieJane, I think the scientific notation could cause many problems in SPSS and similar tools, no? What do others think is the best? I mean we can also just leave it as it is, like this it is as precise as it can be.

Otherwise, I'm also inclined to just use `float256` and get zillion of decimal numbers.

**Comment by KirstieJane** [comment]
I think writing out to a readable number of decimal places is a key feature - for 90% of the users 5 dp will be more than enough.

(I'll stop pinging now and let other team members share their opinions!)

**Comment by rmarkello** [comment]
Looking at @KirstieJane's link to the Python docs, I think we can also use 'g' notation and let Python decide when scientific notation is necessary:

```python
>>> print('{:g}'.format(5.1235125))
5.12351
>>> print('{:g}'.format(0.0051235125))
0.00512351
>>> print('{:g}'.format(0.00000000051235125))
5.12351e-10
```

`g` notation rounds to a given number of significant digits (by default, 6), and decides whether float or scientific notation is more appropriate&mdash;if the exponent in scientific notation would be >=-4, it uses float; otherwise, scientific notation. 

I think this might be a nice compromise between the two options! I'm happy for either 5 or 6 significant digits, too, especially given Kirstie's point:

> (insert something something about MRI being a noisy measure in the first place)

I don't think much more than 5 or 6 sig digits is anything we can reasonably measure with MRI, _especially_ with the type of statistical maps that will be used here :sweat_smile:

**Comment by KirstieJane** [comment]
AH YES. What if I had actually *read* the link that I added 🤦‍♀️ 

`g` format sounds 💯

**Comment by miykael** [comment]
... I opened the link but somehow didn't bother to scroll to `g`` :man_facepalming:
`g` sound perfectly fine. Also with the default 6 dp.

**Comment by miykael** [comment]
Do you want to incorporate those changes @rmarkello?
Also, were you able to investigate the zero... wait. I don't have the issue with the peak values being zeros, anymore. So I guess for now this first point is debugged.

**Comment by miykael** [comment]
This doesn't seem to be an issue anymore (at least I cannot recreate the problem). I think the usage of `np.column_stack` and `np.row_stack` prevent float64 format. By using either of those stack commands all values in numpy array become strings (which causes `float64` to collapse to `float32` if I'm not mistaken). This means also that all elements in the pandas dataframe are of type `object`. And therefore the `to_csv` function cannot consider any kind of number format for floats.

For the cluster summary file this all can be bypassed with the following changes:

```python
@@ -583,11 +583,11 @@ def get_statmap_info(stat_img, atlas='all', voxel_thresh=1.96,
 
     # construct dataframes and reset floats
     atlasnames = [a.atlas for a in atlas]
-    clust_frame = pd.DataFrame(np.row_stack(clust_info),
+    clust_frame = pd.DataFrame(clust_info,
                                columns=['cluster_id',
                                         'peak_x', 'peak_y', 'peak_z',
                                         'cluster_mean', 'volume'] + atlasnames)

@@ -696,10 +696,12 @@ def create_output(filename, atlas='all', voxel_thresh=1.96, cluster_extent=20,
             min_distance=min_distance)
 
         # write output .csv files
-        clust_frame.to_csv(op.join(
-            outdir, '{}_clusters.csv'.format(out_fname)), index=False)
+        clust_frame.to_csv(
+            op.join(outdir, '{}_clusters.csv'.format(out_fname)),
+            index=False, float_format='%g')
```

To correctly format the peak summary file we would need to rewrite the section here https://github.com/miykael/atlasreader/blob/master/atlasreader/atlasreader.py#L490 and here https://github.com/miykael/atlasreader/blob/master/atlasreader/atlasreader.py#L587. And I'm not sure if this is worth all this trouble.
