### ISSUE TITLE
How should `read_atlas_cluster` compute 100%?

### ISSUE THREAD

**Issue by miykael** [miykael/atlasreader#42]
`read_atlas_cluster` currently tells you the extend of a particular cluster, i.e. "100% of the voxels in the cluster are part of the occipital lobe".

What do we want to happen if a cluster is extending into an area that is not part of the atlas? Something as follows: "90% occipital lobe; 10% unknown"?

I think [the code](https://github.com/miykael/atlasreader/blob/master/atlasreader/atlasreader.py#L374) already does this. But we should test it and make sure that this is also the behaviour that we want, as the **cluster.csv** is something new that we introduce.

**Comment by rmarkello** [comment]
Agreed! I think the code does currently output something along those lines, using "no_label" instead of "unknown" (though we can change that, if you'd like). But it is important to test for that, since, as you say, this feature is a new contribution of the repo to the existing tools!

**Comment by miykael** [comment]
I tested it on a stat_map and the code behaves as it should. I.e. the `no_label` part is working as it should.
@rmarkello do you want to close this issue or did you intend that we have an actual test for this?
