### ISSUE TITLE
Should additional plotting functions be included?

### ISSUE THREAD

**Issue by miykael** [miykael/atlasreader#44]
`atlasreader`'s `create_output` function currently takes the following inputs:

 - filename
 - atlas='all'
 - voxel_thresh=1.96
 - cluster_extent=20
 - prob_thresh=5
 - min_distance=None
 - outdir=None

None of them specifies actually how to plot the figures. I like the black background version, but this might not be to everybody's preference. I'm also often changing some of the default plotting variables.

Should we therefore give users the additional option of:
- colorbar=True
- figure=None
- title=None (i.e. on/off)
- annotate=True
- draw_cross=True
- black_bg='auto'
- cmap='virids'
- symmetric_cbar='auto'
- plot_abs=True
- dim='auto'
- alpha=0.7
- vmin=None
- vmax=None
- resampling_interpolation='continuous'

**Comment by rmarkello** [comment]
We could add an [argument group](https://docs.python.org/3/library/argparse.html#argument-groups) to the `argparse` to hold all the plotting settings.

That being said, would this be over-engineering? We're just calling `nilearn.plotting` there, so if someone has the `cluster.csv` and `peaks.csv` then they should be able to make the plots themselves to their preferences. What do you think?

**Comment by danjgale** [comment]
What about using `*kwargs`  in `create_output`? This approach is used in `matplotlib` and `seaborn` to the huge amount of plotting parameters.  Not sure how you would do this from the CLI, but it's super easy to implement in the function.

**Comment by miykael** [comment]
@rmarkello - I agree that over-engineering shouldn't be done. And I mean, if we chose "my preferences" I'm happy with the plotting settings :stuck_out_tongue_closed_eyes: I just think that some additional parameters could help users not to have to use a separate script.

@danjgale - `*kwargs` sounds perfect. I haven't implemented it yet so, I have no idea how to do it. Do you want to go ahead and implement it?

**Comment by danjgale** [comment]
Sure I can work on that!

**Comment by danjgale** [comment]
I have an initial implementation running locally – still have testing to do, etc, so I haven't submitted a PR. This implementation using `kwargs` adds two function parameters to `create_output()`: `glass_plot_kws` and `stat_plot_kws`. Both are `dict`, and function the same way as you would see in `seaborn` (e.g., see the `kws` args [here](https://seaborn.pydata.org/generated/seaborn.distplot.html#seaborn.distplot)). Does that API change seem appropriate to you guys?

**Comment by miykael** [comment]
Thanks, @danjgale - That sounds great like this!

**Comment by danjgale** [comment]
Great! I'll submit the PR once I've gotten some tests in order.

**Comment by rmarkello** [comment]
Closed with #50.
