### ISSUE TITLE
"Unnamed: 0" column in peak.csv file

### ISSUE THREAD

**Issue by miykael** [miykael/atlasreader#45]
Not sure if this is particular to my current case, but I have a noninformative and obsolete column in my csv file called `Unnamed: 0`:

![example_peak](https://user-images.githubusercontent.com/950321/44935266-49267680-ad70-11e8-9b8a-c3f4523a1a5c.png)

Is this just in my case or is this intended?

**Comment by danjgale** [comment]
Looks like it's writing the data frame index to the .csv file in `create_output()`

**Comment by miykael** [comment]
@PeerHerholz - go for it :+1:

**Comment by PeerHerholz** [comment]
Should be done with #51.

**Comment by rmarkello** [comment]
Closed with #51.
