### ISSUE TITLE
Is there a particular order to the clusters / csv files?

### ISSUE THREAD

**Issue by miykael** [miykael/atlasreader#46]
There doesn't seem to be a particular order to the cluster indices. It's neither by peak value, mean value or cluster extent:

![example_peak](https://user-images.githubusercontent.com/950321/44935493-2ba5dc80-ad71-11e8-884b-b77d47fa8c6d.png)

Or am I missing something? Otherwise, I would recommend to go by cluster size (as is standard, I think). Alternative could be peak or average cluster value.

**Comment by rmarkello** [comment]
No no, you don't seem to be missing anything&mdash;I can't see and rhyme or reason to the order. But ordering by cluster size is my preference, too 👍

**Comment by miykael** [comment]
Perfect - I'm also for ordering by cluster size!

**Important note**: The ordering should happen [here](https://github.com/miykael/atlasreader/blob/master/atlasreader/atlasreader.py#L676) to make sure that the cluster IDs for the peak and the cluster CSV file are the same, and that they correspond to the cluster name for the individual plots.
