### ISSUE TITLE
ENH: Switch default filename to atlasreader and adjust relevant documentation

### ISSUE THREAD

**Issue by danjgale** [miykael/atlasreader#68]
This is a bit of a silly issue to submit, which I stumbled upon when I provided `atlasreader.create_output` with a `nibabel.nifti1.Nifti1Image` object instead of a file name.

Currently `create_output` uses the same approach as `nilearn`; it will take "NIfTI-like" inputs. The documentation right now doesn't state that (pretty sure I forgot to add this back at NH18!) so it needs to be updated. As well, when a `nibabel` object is passed, the default output files use a `mniatlasreader` prefix. I suggest changing this to just `atlasreader` to reflect the (new!) name of the project. 

I'll submit a PR shortly unless there's any reason to keep things as they are!

**Comment by rmarkello** [comment]
Closed with #69!
