### ISSUE TITLE
What about 4D images?

### ISSUE THREAD

**Issue by miykael** [miykael/atlasreader#77]
Should `atlasreader` also accept 4D images? At the moment it accepts 4D images, but it only uses the first volume. I think I'm ok with that (for the moment).

Otherwise, I could imagine looping through the volumes and adding an additional postfix after the filename.

Any thoughts?

**Comment by rmarkello** [comment]
I think that accepting 4D images might get a little tricky, so I'm more comfortable leaving it as 3D and just accepting the first volume. Alternatively, we could add a parameter to specify which volume should be used?

**Comment by miykael** [comment]
@rmarkello - Using a parameter is probably the best solution! But in my opinion, we can leave it on the side until someone requests this feature.

Except if you want to implement it :-) Otherwise you can close this issue.

**Comment by miykael** [comment]
Closing this issue for now.
