### ISSUE TITLE
can not install through pip

### ISSUE THREAD

**Issue by EhsanTadayon** [miykael/atlasreader#83]
Hi, 

I'm getting this error while installing through pip: 

Collecting atlasreader
  Could not find a version that satisfies the requirement atlasreader (from versions: )
No matching distribution found for atlasreader

**Comment by miykael** [comment]
Hi @EhsanTadayon. I'm happy to hear that you want to use `atlasreader`. We haven't set it up yet, that you can install `atlasreader` via the web, but if you download the [github repo](https://github.com/miykael/atlasreader/archive/master.zip) and then run `pip install -U .` within the main folder, that should work.

Did this solve your issue?

We're planing on making `atlasreader` pip installable directly from the web until the end of this year.

**Comment by EhsanTadayon** [comment]
Hi @miykael. Thanks. It is definitely a great tool.  I actually went ahead and installed it after cloning it.  

I think the main purpose of atlasreader is to annotate statistical maps using an atlas but I used it to annotate several masks. It works great. The only problem is that since these are masks there is no maximum peak. I didn't go through the package to understand how exactly it works, but I assume it finds the center of the mask for annotation?

**Comment by miykael** [comment]
Hmm.. that's a very good question. I checked the code and it should use `center_of_mass` from `scipy.ndimage` (see [here](https://github.com/miykael/atlasreader/blob/master/atlasreader/atlasreader.py#L227)).

Does it seem to do the right thing with your masks?

**Comment by miykael** [comment]
Hi @EhsanTadayon, `atlasreader` can now be installed via `pip`. Is it alright if I therefore close this issue?

**Comment by miykael** [comment]
I will close this issue for now. Should it not be resolved, I'm happy to reopen it again.
