### ISSUE TITLE
JOSS REVIEW: Update links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by andrewheusser** [miykael/atlasreader#94]
Some of the links in Contributing.md are pointing to rmarkello’s fork of the repo, rather than the main repo (miykael)

**Comment by miykael** [comment]
Thanks @andrewheusser - this will be corrected with https://github.com/miykael/atlasreader/pull/99/commits/6f6acd5c74af7d06effa8495ebd3f1b8839bc4e2.

**Comment by andrewheusser** [comment]
👍
