### ISSUE TITLE
JOSS REVIEW: redundant install requires?

### ISSUE THREAD

**Issue by andrewheusser** [miykael/atlasreader#95]
Install requires are listed in the info.py file as well as a requirements.txt file.  This seems redundant, but perhaps there is a good reason to have them in both places?  Also, the requirements.txt file specifies a version of nilearn (0.5.0a), whereas the info.py version does not.

**Comment by miykael** [comment]
Some services like Docker or mybinder.org prefer `requirements.txt` a file, if I'm not mistaken. Therefore, I would like to leave them both in, if this is alright?

And I've updated the `nilearn` version in `requirements.txt` with https://github.com/miykael/atlasreader/pull/99/commits/6fae3cc1bebe27124489542f657f8000c186de6d, to make it congruent with `info.py`.

**Comment by andrewheusser** [comment]
Fine to leave them both in, I was just curious why. The docker justification seems reasonable to me
