### ISSUE TITLE
JOSS REVIEW: typo in example notebook

### ISSUE THREAD

**Issue by andrewheusser** [miykael/atlasreader#96]
[`atlasreader`](https://github.com/miykael/atlasreader) is a Python interface that generats coordinate tables and region labels from statistical MRI images.

generats -> generates

**Comment by miykael** [comment]
Will be corrected with https://github.com/miykael/atlasreader/pull/99/commits/0743a976fb764d44fafe646b6a6fa9c524b5536c.

**Comment by andrewheusser** [comment]
👍
