### ISSUE TITLE
JOSS REVIEW: repo is large

### ISSUE THREAD

**Issue by andrewheusser** [miykael/atlasreader#97]
Repo is rather large (~34MB) because the atlases are included.   Not required for acceptance (by me at least), but i'd suggest moving them to a separate location and fetch them programmatically instead storing a local copy in the repo.  Also, are there any license considerations of the atlases given that you  copied them into the repo? I see the warning that each atlas has its own license, but have you made certain its acceptable to store a copy of them in your package?

**Comment by miykael** [comment]
The repo itself might be big, but the installed package is only ~13MB in size. We thought about having the atlases in a separate location but decided that 13MB is acceptable for a neuroimaging toolbox. Also, having the atlases within the package means that users do not need to download them every other time.

Concerning the license issue: The atlases contained in `atlasreader` are all publicly available, and under licenses that allow usage and sharing as long as the original licenses are clearly linked. For this reason we've written the summary readme (https://github.com/miykael/atlasreader/blob/master/atlasreader/data/README.md) and linked to it as well, in the information message, which is shown everytime `atlasreader` is executed.

We've also looked into how comparable toolboxes, such as [`nilearn`](https://github.com/nilearn/nilearn/tree/master/nilearn/datasets) handle this issue, but didn't find a better approach.

The solution is surely not ideal and I'm happy to discuss this further if you want.

**Comment by andrewheusser** [comment]
Not necessary, I think it's reasonable to keep them contained in the toolbox.  Though it's something to consider if the number of supported atlases grow.

**Comment by miykael** [comment]
Yes, I agree. Thank you for bringing it to our attention.
